export const ORDER_COUNT_REQUEST = 'ORDER_COUNT_REQUEST'
export const ORDER_COUNT_SUCCESS = 'ORDER_COUNT_SUCCESS'
export const ORDER_COUNT_FAIL = 'ORDER_COUNT_FAIL'

export const FEEDBACK_COUNT_REQUEST = 'FEEDBACK_COUNT_REQUEST'
export const FEEDBACK_COUNT_SUCCESS = 'FEEDBACK_COUNT_SUCCESS'
export const FEEDBACK_COUNT_FAIL = 'FEEDBACK_COUNT_FAIL'

export const OFFER_COUNT_REQUEST = 'OFFER_COUNT_REQUEST'
export const OFFER_COUNT_SUCCESS = 'OFFER_COUNT_SUCCESS'
export const OFFER_COUNT_FAIL = 'OFFER_COUNT_FAIL'

export const USER_COUNT_REQUEST = 'USER_COUNT_REQUEST'
export const USER_COUNT_SUCCESS = 'USER_COUNT_SUCCESS'
export const USER_COUNT_FAIL = 'USER_COUNT_FAIL'

export const PRODUCT_COUNT_REQUEST = 'PRODUCT_COUNT_REQUEST'
export const PRODUCT_COUNT_SUCCESS = 'PRODUCT_COUNT_SUCCESS'
export const PRODUCT_COUNT_FAIL = 'PRODUCT_COUNT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'